// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function addIfUniq(acc, el) {
  if (acc.indexOf(el) === -1) {
    return acc.concat([el]);
  } else {
    return acc;
  }
}

function intersectWithDoublicates(arr1, arr2) {
  return arr1.filter(function (el) {
                return arr2.some(function (i) {
                            return Caml_obj.equal(i, el);
                          });
              }).reduce(addIfUniq, []);
}

exports.addIfUniq = addIfUniq;
exports.intersectWithDoublicates = intersectWithDoublicates;
/* No side effect */
