// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Yandex1$YandexTasks = require("../src/Yandex1.bs.js");
var Promise$RescriptMocha = require("rescript-mocha/lib/js/src/Promise.bs.js");

Mocha$RescriptMocha.describe("Yandex1 task methods")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.describe("addIfUniq [1, 2, 3] 2")(undefined, undefined, undefined, (function (param) {
                Mocha$RescriptMocha.it("addIfUniq")(undefined, undefined, undefined, (function (param) {
                        if (Caml_obj.equal(Yandex1$YandexTasks.addIfUniq([
                                    1,
                                    2,
                                    3
                                  ], 2), [
                                1,
                                2,
                                3
                              ])) {
                          return ;
                        }
                        throw {
                              RE_EXN_ID: "Assert_failure",
                              _1: [
                                "Yandex1.test.res",
                                8,
                                12
                              ],
                              Error: new Error()
                            };
                      }));
              }));
      }));

var it$p = Promise$RescriptMocha.it;

var it_skip$p = Promise$RescriptMocha.it_skip;

exports.it$p = it$p;
exports.it_skip$p = it_skip$p;
/*  Not a pure module */
